apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: hello-task
  namespace: test
spec:
  steps:
    - name: echo-hello-message
      image: alpine:latest
      script: |
        #!/bin/sh
        echo "Hello World!"